<a href="https://colab.research.google.com/github/KeiandraK/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Keiandra_King_LS_DS_112_Make_Features_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [0]:
import numpy as np
import pandas as pd

In [0]:
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
!unzip LoanStats_2018Q4.csv.zip

--2019-10-02 03:58:26--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip.5’

LoanStats_2018Q4.cs     [                 <=>]  21.62M   892KB/s    in 25s

2019-10-02 03:58:52 (893 KB/s) - ‘LoanStats_2018Q4.csv.zip.5’ saved [22667400]

Archive:  LoanStats_2018Q4.csv.zip
replace LoanStats_2018Q4.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: n

In [0]:
!head LoanStats_2018Q4.csv

Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
"id","member_id","loan_amnt","funded_amnt","funded_amnt_inv","term","int_rate","installment","grade","sub_grade","emp_title","emp_length","home_ownership","annual_inc","verification_status","issue_d","loan_status","pymnt_plan","url","desc","purpose","title","zip_code","addr_state","dti","delinq_2yrs","earliest_cr_line","inq_last_6mths","mths_since_last_delinq","mths_since_last_record","open_acc","pub_rec","revol_bal","revol_util","total_acc","initial_list_status","out_prncp","out_prncp_inv","total_pymnt","total_pymnt_inv","total_rec_prncp","total_rec_int","total_rec_late_fee","recoveries","collection_recovery_fee","last_pymnt_d","last_pymnt_amnt","next_pymnt_d","last_credit_pull_d","collections_12_mths_ex_med","mths_since_last_major_derog","policy_code","application_type","annual_inc_joint","dti_joint","verification_status_joint","acc_now_delinq","tot_coll_amt","tot_cur_bal","open_acc_6m","open_act_il","open_il_12m","open_il_24m","mths_since_rcnt_il","total_bal_il","il_util","open_rv_12m","open_rv_24m","max_bal_bc","all_util","total_rev_hi_lim","inq_fi","total_cu_tl","inq_last_12m","acc_open_past_24mths","avg_cur_bal","bc_open_to_buy","bc_util","chargeoff_within_12_mths","delinq_amnt","mo_sin_old_il_acct","mo_sin_old_rev_tl_op","mo_sin_rcnt_rev_tl_op","mo_sin_rcnt_tl","mort_acc","mths_since_recent_bc","mths_since_recent_bc_dlq","mths_since_recent_inq","mths_since_recent_revol_delinq","num_accts_ever_120_pd","num_actv_bc_tl","num_actv_rev_tl","num_bc_sats","num_bc_tl","num_il_tl","num_op_rev_tl","num_rev_accts","num_rev_tl_bal_gt_0","num_sats","num_tl_120dpd_2m","num_tl_30dpd","num_tl_90g_dpd_24m","num_tl_op_past_12m","pct_tl_nvr_dlq","percent_bc_gt_75","pub_rec_bankruptcies","tax_liens","tot_hi_cred_lim","total_bal_ex_mort","total_bc_limit","total_il_high_credit_limit","revol_bal_joint","sec_app_earliest_cr_line","sec_app_inq_last_6mths","sec_app_mort_acc","sec_app_open_acc","sec_app_revol_util","sec_app_open_act_il","sec_app_num_rev_accts","sec_app_chargeoff_within_12_mths","sec_app_collections_12_mths_ex_med","sec_app_mths_since_last_major_derog","hardship_flag","hardship_type","hardship_reason","hardship_status","deferral_term","hardship_amount","hardship_start_date","hardship_end_date","payment_plan_start_date","hardship_length","hardship_dpd","hardship_loan_status","orig_projected_additional_accrued_interest","hardship_payoff_balance_amount","hardship_last_payment_amount","debt_settlement_flag","debt_settlement_flag_date","settlement_status","settlement_date","settlement_amount","settlement_percentage","settlement_term"
"","","20000","20000","20000"," 36 months"," 14.47%","688.13","C","C2","bus driver","4 years","OWN","52000","Source Verified","Dec-2018","Current","n","","","debt_consolidation","Debt consolidation","681xx","NE","30.65","1","Jun-1979","2","15","","6","0","15048","73%","22","w","15777.74","15777.74","6104.74","6104.74","4222.26","1882.48","0.0","0.0","0.0","Sep-2019","688.13","Oct-2019","Sep-2019","0","","1","Individual","","","","0","0","33157","0","2","1","1","8","18109","44","1","2","8628","73","20700","1","1","4","3","5526","5175","73","0","0","141","474","10","8","0","10","15","1","15","0","4","4","11","12","8","4","14","4","6","","0","0","2","95","50","0","0","61699","33157","20700","40999","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","25000","25000","25000"," 60 months"," 16.14%","609.82","C","C4","Production Manager","5 years","MORTGAGE","45000","Not Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","703xx","LA","37.09","0","Sep-2003","0","","","7","0","8901","36.8%","21","w","0.00","0.00","26653.1675796436","26653.17","25000.00","1653.17","0.0","0.0","0.0","Apr-2019","24857.33","","May-2019","0","","1","Individual","","","","0","1303","49524","0","2","1","2","7","40623","82","0","0","7830","67","24200","2","0","1","2","7075","10465","43.7","0","0","161","162","45","7","4","96","","7","","0","2","3","3","5","7","5","10","3","7","0","0","0","1","100","33.3","0","0","73683","49524","18600","49483","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","26500","26500","26500"," 60 months"," 11.31%","580.28","B","B3","Compliance Director","10+ years","MORTGAGE","134000","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","747xx","OK","18.91","0","Dec-2006","2","","","17","0","43640","65.4%","37","w","23410.70","23410.70","5197.54","5197.54","3089.30","2108.24","0.0","0.0","0.0","Sep-2019","580.28","Oct-2019","Sep-2019","0","","1","Individual","","","","0","0","381100","3","3","2","2","4","64335","46","1","3","10115","58","66700","2","1","7","6","22418","14577","70.4","0","0","114","144","3","3","4","22","","2","","0","8","10","9","10","7","13","26","10","17","0","0","0","4","100","66.7","0","0","430403","107975","49300","88875","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","10400","10400","10400"," 36 months"," 12.98%","350.32","B","B5","Program Support Assistant ","10+ years","MORTGAGE","56099","Source Verified","Dec-2018","Current","n","","","credit_card","Credit card refinancing","800xx","CO","20.92","0","Jul-2013","2","32","67","8","1","1669","9.8%","10","w","8164.57","8164.57","3141.63","3141.63","2235.43","906.20","0.0","0.0","0.0","Sep-2019","350.32","Oct-2019","Sep-2019","0","","1","Individual","","","","0","0","39564","4","2","1","2","1","37895","92","3","6","725","36","17000","1","0","4","8","4946","15331","9.8","0","0","65","57","1","1","0","1","","0","32","0","3","3","6","6","3","6","7","3","8","0","0","0","4","90","0","1","0","60709","39564","17000","43709","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","35000","35000","35000"," 60 months"," 12.98%","796","B","B5","Sr. Vice President -Risk Manager","7 years","MORTGAGE","211646","Source Verified","Dec-2018","Fully Paid","n","","","debt_consolidation","Debt consolidation","797xx","TX","15.09","0","Sep-1985","0","77","","13","0","55944","74.9%","39","w","0.00","0.00","36266.741551619","36266.74","35000.00","1266.74","0.0","0.0","0.0","Apr-2019","34712.6","","Sep-2019","0","","1","Joint App","272421","15.89","Source Verified","0","0","420931","1","3","1","2","5","26570","51","0","2","24795","65","74700","1","6","1","4","32379","8677","85.5","0","0","152","399","21","5","6","21","77","12","77","0","6","8","6","11","14","9","19","8","13","0","0","0","1","97.4","66.7","0","0","516204","82514","59700","51904","88364","Sep-1985","0","6","19","53.4","2","29","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","20000","20000","20000"," 36 months","  7.56%","622.68","A","A3","Teacher","10+ years","MORTGAGE","100000","Not Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","982xx","WA","18.92","0","Feb-1999","0","48","","9","0","25416","29.9%","19","w","0.00","0.00","20215.79243","20215.79","20000.00","215.79","0.0","0.0","0.0","Feb-2019","20228.39","","Feb-2019","0","","1","Joint App","190000","11.75","Not Verified","0","0","515779","1","2","0","1","13","46153","71","1","2","9759","39","85100","2","2","0","5","57309","59684","29.9","0","0","171","238","1","1","5","1","","13","48","0","5","5","5","6","5","5","9","5","9","0","0","0","1","94.7","20","0","0","622183","71569","85100","74833","43287","Aug-1998","0","3","10","29.7","2","7","0","0","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","13000","13000","13000"," 36 months"," 17.97%","469.79","D","D1","Help Tech Supervisor","10+ years","MORTGAGE","92360","Source Verified","Dec-2018","Current","n","","","home_improvement","Home improvement","300xx","GA","27.44","0","Sep-2006","1","68","","18","0","32020","49.6%","30","w","10370.35","10370.35","4208.64","4208.64","2629.65","1578.99","0.0","0.0","0.0","Sep-2019","469.79","Oct-2019","Sep-2019","0","","1","Individual","","","","0","0","131919","1","2","1","3","4","17310","60","0","2","6116","53","64600","1","4","1","5","7760","7140","70.7","0","0","120","147","16","4","2","18","","4","70","0","5","12","6","7","6","15","22","12","18","0","0","0","1","90","66.7","0","0","190803","49330","24400","28861","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""
"","","12000","12000","12000"," 60 months"," 14.47%","282.16","C","C2","Assistant Athletic Director of Marketing","1 year","RENT","67000","Not Verified","Dec-2018","Fully Paid","n","","","credit_card","Credit card refinancing","231xx","VA","28.39","0","Aug-2009","1","","","9","0","10018","50.9%","34","w","0.00","0.00","13140.1266634624","13140.13","12000.00","1140.13","0.0","0.0","0.0","Sep-2019","11169.83","","Sep-2019","0","","1","Individual","","","","0","0","184578","1","4","2","3","5","174560","97","0","1","4615","87","19700","1","1","2","4","20509","9682","50.9","0","0","112","80","23","5","0","23","","5","","0","3","3","5","5","26","5","8","3","9","0","0","0","2","100","0","0","0","183897","184578","19700","164197","","","","","","","","","","","","N","","","","","","","","","","","","","","","N","","","","","",""

In [0]:
df= pd.read_csv('LoanStats_2018Q4.csv', header=1)
print(df.shape)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,123,124,125,128,129,130,133) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(128414, 144)

    id  member_id  ...  settlement_percentage  settlement_term
0  NaN        NaN  ...                    NaN              NaN
1  NaN        NaN  ...                    NaN              NaN
2  NaN        NaN  ...                    NaN              NaN
3  NaN        NaN  ...                    NaN              NaN
4  NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [0]:
df.dtypes[:20]

id                      object
member_id              float64
loan_amnt              float64
funded_amnt            float64
funded_amnt_inv        float64
term                    object
int_rate                object
installment            float64
grade                   object
sub_grade               object
emp_title               object
emp_length              object
home_ownership          object
annual_inc             float64
verification_status     object
issue_d                 object
loan_status             object
pymnt_plan              object
url                    float64
desc                   float64
dtype: object

In [0]:
df['loan_status'][:10]

0       Current
1    Fully Paid
2       Current
3       Current
4    Fully Paid
5    Fully Paid
6       Current
7    Fully Paid
8       Current
9       Current
Name: loan_status, dtype: object

In [0]:
df['term'].fillna

<bound method Series.fillna of 0          36 months
1          60 months
2          60 months
3          36 months
4          60 months
5          36 months
6          36 months
7          60 months
8          36 months
9          60 months
10         60 months
11         36 months
12         36 months
13         36 months
14         36 months
15         36 months
16         36 months
17         36 months
18         60 months
19         36 months
20         60 months
21         36 months
22         60 months
23         36 months
24         60 months
25         60 months
26         60 months
27         36 months
28         36 months
29         60 months
             ...
128384     36 months
128385     60 months
128386     36 months
128387     60 months
128388     36 months
128389     36 months
128390     36 months
128391     36 months
128392     36 months
128393     36 months
128394     36 months
128395     36 months
128396     60 months
128397     60 months
128398     60 months
128399     36 months
128400     60 months
128401     36 months
128402     60 months
128403     36 months
128404     60 months
128405     36 months
128406     36 months
128407     36 months
128408     36 months
128409     36 months
128410     36 months
128411     36 months
128412           NaN
128413           NaN
Name: term, Length: 128414, dtype: object>

In [0]:
df['term'].apply(str)
df['term']= df['term'].str.strip('months')
df['term'][:10]

0     36
1     60
2     60
3     36
4     60
5     36
6     36
7     60
8     36
9     60
Name: term, dtype: object

In [0]:
df.head(5)

    id  member_id  ...  settlement_percentage  settlement_term
0  NaN        NaN  ...                    NaN              NaN
1  NaN        NaN  ...                    NaN              NaN
2  NaN        NaN  ...                    NaN              NaN
3  NaN        NaN  ...                    NaN              NaN
4  NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [0]:
#loan_status_is_great. It should contain the integer 1 if loan_status is "Current" or "Fully Paid." Else it should contain the integer 0
df['loan_status_is_great']=df['loan_status'].str.contains("Current","Fully Paid")

In [0]:
df.head(5)

    id  member_id  ...  settlement_term  loan_status_is_great
0  NaN        NaN  ...              NaN                  True
1  NaN        NaN  ...              NaN                 False
2  NaN        NaN  ...              NaN                  True
3  NaN        NaN  ...              NaN                  True
4  NaN        NaN  ...              NaN                 False

[5 rows x 145 columns]

In [272]:
subdition= df['loan_status_is_great']=df['loan_status'].str.contains("Current","Fully Paid")==int(1)
subdition.head(5)

0     True
1    False
2     True
3     True
4    False
Name: loan_status, dtype: bool

In [304]:
if df['loan_status_is_great']==True:
  print(1)
  else df['loan_status_is_great']=False
    print(0)
# I was not able to figure this one out for some reason every verions of code I 
# write comes back with some type of error!

SyntaxError: ignored

In [313]:
#last_pymnt_d_month and last_pymnt_d_year columns.
df['last_pymnt_d_month']=df['last_pymnt_d']
df['last_pymnt_d_month'][:5]

0    Sep-2019
1    Apr-2019
2    Sep-2019
3    Sep-2019
4    Apr-2019
Name: last_pymnt_d_month, dtype: object

In [322]:
df['last_pymnt_d_year']=df['last_pymnt_amnt']
df['last_pymnt_d_year'][:5]

0      688.13
1    24857.33
2      580.28
3      350.32
4    34712.60
Name: last_pymnt_d_year, dtype: float64

In [321]:
df.head(2)

    id  member_id  ...  last_pymnt_d_month  last_pymnt_d_year
0  NaN        NaN  ...            Sep-2019             688.13
1  NaN        NaN  ...            Apr-2019           24857.33

[2 rows x 147 columns]

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [0]:
# !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

In [0]:
# %cd instacart_2017_05_01